#!/bin/bash

python translate.py --site $POPCLIP_OPTION_SITE  --destlang $POPCLIP_OPTION_DESTLANG --motherlang $POPCLIP_OPTION_MOTHERLANG --toclipboard $POPCLIP_OPTION_TOCLIPBOARD --location $POPCLIP_OPTION_LOCATION $POPCLIP_URLENCODED_TEXT
